version: '3.8'

services:
  estock_pg:
    image: postgres:10.5
    restart: always
    container_name: estock_pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  estock_mongo:
    image: mongo:5.0
    container_name: estock_mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/var/lib/mongodb/data
  
  estock:
    container_name: estock_api
    image: estock-api-image
    ports:
      - '5080:5080'
      - '8080:8080'
    links:
      - estock_mongo
      - estock_pg
    depends_on:
      - estock_mongo
      - estock_pg
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  postgres:
  mongo: